# Generated by setup-terraform-backend.sh - shared remote state backend.
# Do not edit the values below by hand; re-run setup-terraform-backend.sh
# with the same options instead so every developer stays in sync.
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-terraform-state-dev"
    storage_account_name = "sttfstate369d94e0"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
    use_azuread_auth     = true
  }
}
